### PR TITLE
Update guides for 0.10.0

### PR DESCRIPTION
**Pull request by paulcsmith**

### CODE REVIEW

**Comment by jwoertink** [comment]
@paulcsmith One thing I haven't seen (maybe I missed) was documenting how to create a custom task, what they are used for, or even the fact that `lucky routes` is a thing. Is that something you think could go in this PR? Or would you like a separate PR for that?

**Comment by paulcsmith** [comment]
@jwoertink Yes! That would be wonderful to add, but I think it could be a separate guide called `Tasks in Lucky` and would first show some of the built-in tasks and then show how to create and run your own.

There is nothing specific to this release so it could be done at any time

**Comment by jwoertink** [comment]
Cool. In that case, I'll work on something.

**Comment by paulcsmith** [comment]
Awesome! :D

**Pull request merged**
