### PR TITLE
Extract Sass variables

### PR DESCRIPTION
**Pull request by paulcsmith**
Here is what the page looks like

screen shot 2017-09-29 at 11 24 10 am

### CODE REVIEW

**Comment by sardaukar** [comment]
Should we Ralph it up and add a link to thoughtbot.com ?

**Comment by paulcsmith** [comment]
@sardaukar Good idea. I'll add a GitHub and thoughtbot link to it

**Comment by paulcsmith** [comment]
screen shot 2017-09-29 at 3 34 57 pm

**Comment by sardaukar** [comment]
:ok_hand:

**Pull request merged**
