### PR TITLE
Update guide with new patch and trace routing methods

### PR DESCRIPTION
**Pull request by joeldrapper**
Bring the Acrtions and Routing guide up-to-date with the new routing methods introduced in luckyframework/lucky/pull/552.

### CODE REVIEW

**Comment by edwardloveall** [comment]
Awesome! Thanks for this. I think we'll wait to merge this until [your PR](https://github.com/luckyframework/lucky/pull/552) is actually in a released version of Lucky so no one is trying to use these methods in the current version.

Please don't hesitate to remind me if I forget 😉

**Review by edwardloveall — APPROVED** [review]

**Comment by jwoertink** [comment]
@edwardloveall ping 😉  [this](https://github.com/luckyframework/lucky/pull/552) is merged

**Comment by edwardloveall** [comment]
Thanks for the reminder! I'll take a look at this tonight.

**Comment by edwardloveall** [comment]
Done! Congrats @joeldrapper and thanks for your contribution! 🎉

**Comment by paulcsmith** [comment]
Sorry I just noticed this! I think we may want to revert this. The commit is in Lucky master, but is not in an official release. So if someone tries to use this on v0.11 of Lucky it won't work.

Could we revert the commit and re-open the PR? Then we can merge it in once a new Lucky version is released

**Comment by edwardloveall** [comment]
Ah yeah, my bad. I even said "released version of Lucky" in my comment. Sorry about this @joeldrapper. We'll revert and re commit once this version of Lucky's released.

**Pull request merged**
