### PR TITLE
Rename inner to content

### PR DESCRIPTION
**Pull request by jdbann**
Closes https://github.com/luckyframework/lucky_cli/issues/158

### CODE REVIEW

**Comment by paulcsmith** [comment]
Thank you very much!

**Comment by paulcsmith** [comment]
@jdbann If/when you have a moment, could you rebase and force push this? Don't worry uf you don't have time, LMK and I can do it 👍

**Comment by paulcsmith** [comment]
Someone was tripped up by this so I rebased and committer here: https://github.com/luckyframework/website/commit/1c736b5deeb5d8a45ea32bf527cf1ac8cc9a401b

Thanks @jdbann for tackling this!

**Comment by jdbann** [comment]
Busy work week! Sorry I missed your request. Glad it's in 👍

**Pull request closed without merging**
